### ISSUE TITLE
Question about design choices

### ISSUE THREAD

**Issue by DutchJelly** [jhewlett/react-reversi#2]
This isn't really an issue in the project, but I'm just curious about the design choices that are made in this project. 

I see that the react components mostly consist of html and styling. The main javascript code is implemented in the ``./libs`` directory. Personally I thought that react was meant to combine the javascript code with the html, without the use of additional utility classes or functions. 

Currently I'm trying to learn react myself, and can't quite figure out when to make global utility classes or functions for the implementation of the functionality of the components. So why did you choose to seperate the react components from the logic involved?

Feel free to remove this issue: it's not an issue!

**Comment by jhewlett** [comment]
@DutchJelly Hi, sorry this took a while to respond to.

Part of this is simply historical. It started out as a project [in plain javascript](https://github.com/jhewlett/react-reversi/tree/82fc496d0133d23ff1dcc950adbeb7b5b9772082/src), with DOM manipulation. Later, I ported it to React. So I replaced the view layer (DOM manipulation) with React, and all of the business logic and state management was outside of the components.

The other reason is that I consider it a good practice to keep business logic out of React components. It's fine for _view_ logic to live in there, like opening and closing a drop-down, and keeping track of whether it's currently open or closed. But anything more complex than that probably out to live elsewhere. This makes it easier to test, without having to render any views, and just gives you a nicer separation of concerns. (This initial separation of concerns is part of what made it easy to move to React, I mainly had to modify the view layer.)

If I were to do this in React this from scratch, it's possible that more of the business logic would have ended up living in redux actions and reducers. This is probably fine and still gives you pretty good separation and testability.

Does that help?
